referral_project/urls.py
from django.contrib import admin
from django.urls import path,include
from reff_no_api import urls as no_api_urls
urlpatterns = [
    path('ritik_sinha_admin/', admin.site.urls),
    path('',include(no_api_urls))
]


from django.views.static import serve
from django.conf import settings
urlpatterns += [
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT}),
]

reff_no_api/urls.py
from django.urls import path
from .views import *
urlpatterns = [
   path('', home, name='home'),
#    path('<str:cust_str>', home_str, name='home_str'),
   path('login/', user_login, name='user_login'),
   path('logout/', user_logout, name='user_logout'),
   path('sign_up/', user_register.as_view(), name='user_register'),
   path('sign_up/<str:ref_id>/', user_register.as_view(), name='ref_register'),
   path('profile/', user_dashboard, name='user_dash'),
   path('admin_login/',admin_login, name='admin_login'),
   path('admin_dash/',admin_dash, name='admin_dash'),
   path('add_points/<int:usr_str_id>/',add_points, name='add_points'),
   path('valid_user/<str:usr_name>/',username_validate, name='valid_user'),
   path('valid_mob/<str:mob_no>/',mobile_validate, name='valid_mob'),
   path('delete_user/<int:usr_id>/',delete_user, name='delete_user'),
]

reff__api/models.py
from django.db import models

# Create your models here.

reff_no_api/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser# Create your models here.
from .manager import CustomUserManager
class CustomUser(AbstractUser):
    username = models.CharField(max_length=255, unique=True)
    first_name= models.CharField(max_length=255)
    last_name= models.CharField(max_length=255)
    email= models.EmailField(max_length=255, unique=True)
    mobile_no= models.CharField(max_length=255, unique=True)
    password= models.CharField(max_length=255)
    unique_id= models.CharField(max_length=255, unique=True)
    created_at= models.DateTimeField(auto_now_add=True)
    objects= CustomUserManager()
    
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['mobile_no',  'first_name', 'last_name', 'password']
    
    def __str__(self) -> str:
        return self.username
    def save(self, *args, **kwargs):
        if not self.unique_id:
            self.unique_id =  self.mobile_no+'YEP'
        super().save(*args, **kwargs)
class UserStructure(models.Model):
    user_id= models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    ref_by_user_id= models.ForeignKey(CustomUser, on_delete=models.PROTECT, related_name='ref_by_user_id', blank=True, null=True)
    points= models.IntegerField(default=0)
    child_branch=models.ManyToManyField(CustomUser, related_name='child_branch', blank=True)

    def __str__(self) -> str:
        return self.user_id.username
    @property
    def child_count(self):
        return self.child_branch.count()

reff__api/views.py
from django.shortcuts import render

# Create your views here.

reff_no_api/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from .models import CustomUser, UserStructure
from django.contrib.auth.decorators import login_required
from django.views import View
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.http import JsonResponse
# Create your views here.
def home(request):
    return render(request, 'home.html')
def home_str(request,cust_str):
    if CustomUser.objects.filter(unique_id=cust_str).exists():
        return redirect('ref_register',cust_str)
    
    return redirect('home')
def user_login(request):
    if request.method == 'POST':
        username= request.POST.get('username')
        password= request.POST.get('password')
        authenticated_user = authenticate(username=username, password=password)
        print(authenticated_user,username,password)
        if authenticated_user is not None:
            login(request, authenticated_user)
            return redirect('user_dash')
    return render(request, 'user_login.html')
def user_logout(request):
    logout(request)
    return redirect('home')

@login_required(login_url='user_login')
def user_dashboard(request):
    user_structure = UserStructure.objects.get(user_id=request.user)
    data={
        'user_structure':user_structure
    }
    return render(request, 'user_dash.html',data)
class user_register(View):
    def get(self, request,ref_id=None, *args, **kwargs):
        print(ref_id)
        user=request.user
        if user.is_authenticated:
            logout(request)
        if ref_id:
            ref_user=CustomUser.objects.filter(unique_id=ref_id)
            if ref_user.exists():
                return render(request, 'user_register.html',{'ref_user':ref_user.last()})
            else:
                return redirect('home')
        return render(request, 'user_register.html')
    def post(self, request,ref_id=None, *args, **kwargs):
        username= request.POST.get('username')
        password= request.POST.get('password')
        email= request.POST.get('email', None)
        mobile_no= request.POST.get('mobile_no')
        first_name= request.POST.get('first_name')
        last_name= request.POST.get('last_name')
        if username:
            user_crt=CustomUser.objects.create_user(username=username, password=password, email=email, mobile_no=mobile_no, first_name=first_name, last_name=last_name)
            if ref_id:
                ref_user=get_object_or_404(CustomUser, unique_id=ref_id)
                UserStructure.objects.create(user_id=user_crt, ref_by_user_id=ref_user)
                ref_usr_str=UserStructure.objects.get(user_id=ref_user)
                ref_usr_str.child_branch.add(user_crt)
            else:
                UserStructure.objects.create(user_id=user_crt)
            login(request, CustomUser.objects.get(username=username))
            return redirect('user_dash')
        else:
            return render(request, 'user_register.html')


def admin_login(request):
    user=request.user
    if user.is_authenticated and user.groups.filter(name='admin').exists():
        return redirect('admin_dash')
    elif user.is_authenticated:
        logout(request)
        return redirect('admin_login')
    if request.method == 'POST':
        username= request.POST.get('username')
        password= request.POST.get('password')
        authenticated_user = authenticate(username=username, password=password)
        print(authenticated_user,username,password)
        if authenticated_user is not None and authenticated_user.groups.filter(name='admin').exists():
            login(request, authenticated_user)
            return redirect('admin_dash')
    return render(request, 'admin_login.html')
@login_required(login_url='admin_login')
def admin_dash(request):
    user=request.user
    if user.groups.filter(name='admin').exists():
        pass
    else:
        messages.error(request, 'You are not admin')
        return redirect('admin_login')
    all_str=UserStructure.objects.filter(user_id__is_superuser=False).order_by('-id')
    data={
        'all_str':all_str,
        'total_count':all_str.count()
    }
    return render(request, 'admin_dash.html',data)

def add_points(request,usr_str_id):
    usr_str=UserStructure.objects.get(id=usr_str_id)
    if request.method == 'POST':
        points= request.POST.get('points')
        usr_str.points+=int(points)
        usr_str.save()
        return redirect('admin_dash')
    

def username_validate(request, usr_name):
    usern = CustomUser.objects.filter(username=usr_name).exists()
    if usern:
        return JsonResponse({'is_valid': False})
    else:
        return JsonResponse({'is_valid': True})

def mobile_validate(request, mob_no):
    mob = CustomUser.objects.filter(mobile_no=mob_no).exists()
    if mob:
        return JsonResponse({'is_valid': False})
    else:
        return JsonResponse({'is_valid': True})

def delete_user(request,usr_id):
    user=CustomUser.objects.get(id=usr_id)
    if user.groups.filter(name='admin').exists():
        return redirect('admin_dash')
    user.delete()
    return redirect('admin_dash')

reff_no_api/templates/admin_dash.html
{% extends 'base.html' %}

{% block head %}
<script>
    function searchCustomer() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("searchInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("customerTable");
        tr = table.getElementsByTagName("tr");
    
        for (i = 0; i < tr.length; i++) {
          // Adjust the index to match the "Medicine Name" column (index 0)
          td = tr[i].getElementsByTagName("td")[0];
          if (td) {
            txtValue = td.textContent || td.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
              tr[i].style.display = "";
            } else {
              tr[i].style.display = "none";
            }
          }
        }
      }
      function searchPhone() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("searchInput2");
        filter = input.value.toUpperCase();
        table = document.getElementById("customerTable");
        tr = table.getElementsByTagName("tr");
    
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[3];
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    };
</script>
{% endblock head %}
    
{% block content %}
    <div class="container">
        <h1>
            Admin Dashboard
        </h1>
        <h3 class="text-end">
            Total Count={{ total_count }}
        </h3>
        <div class="card">

        
            <!-- Search Bar  -->
            <div class="row m-3">
                <div class="col">
                <input
                    type="text"
                    class="form-control"
                    id="searchInput"
                    onkeyup="searchCustomer()"
                    placeholder="Search by Customer Name"
                />
                </div>
                <div class="col">
                    <input
                    class="form-control"
                    type="text"
                    id="searchInput2"
                    onkeyup="searchPhone()"
                    placeholder="Search by phone number"
                    />
                </div>
            <!-- Search Bar End  -->
            </div>
            <h4>
                Members List
            </h4>
            <table class="table" id="customerTable">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">DateTime</th>
                        <th scope="col">Referred By</th>
                        <th scope="col">Mobile No</th>
                        <th scope="col">Email</th>
                        <th scope="col">Team Count</th>
                        <th scope="col">Points</th>
                        <th scope="col">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    
                    {% for usr in all_str %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal{{ usr.id }}">
                            {{ usr.user_id.first_name }} {{ usr.user_id.last_name }}
                        </button></td>
                        <td>{{ usr.user_id.created_at }}</td>
                        <td>{{ usr.ref_by_user_id.first_name }} {{ usr.ref_by_user_id.last_name }}</td>
                        <td>{{ usr.user_id.mobile_no }}</td>
                        <td>{{ usr.user_id.email }}</td>
                        <td>{{ usr.child_count }}</td>
                        <td>{{ usr.points}} </td>
                        <td>
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal{{ usr.id }}">
                                Delete
                            </button>
                            
                        </td>
                    </tr>
                    
                    
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal{{ usr.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">{{ usr.user_id.first_name }} {{ usr.user_id.last_name }}</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            
                        </div>
                        <p class="text-center"><b>Total Points: {{ usr.points }} </b></p>
                            <div class="modal-body">
                                <h4>Refers</h4>
                                    {% for child in usr.child_branch.all %}
                                    <ul class="list-group list-group-horizontal">
                                        <li class="list-group-item">{{ forloop.counter }}</li>
                                        <li class="list-group-item">{{ child.first_name }} {{ child.last_name }}</li>
                                        <li class="list-group-item">{{ child.mobile_no }}</li>
                                        <li class="list-group-item">{{ child.email }}</li>
                                    </ul>
                                    {% endfor %}
                            </div>
                            <div class="modal-footer">
                                <form action="{% url 'add_points' usr.id %}" method="post">
                                    {% csrf_token %}
                                    <label for="points">Add Points</label>
                                    <input type="number" name="points" id="points">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <button type="submit" class="btn btn-primary">Add</button>
                                </form>
                            </div>
                        </div>
                        </div>
                    </div>
                    <div class="modal fade" id="deleteModal{{ usr.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">{{ usr.user_id.first_name }} {{ usr.user_id.last_name }}</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            
                        </div>
                            <div class="modal-body">
                                <h4>Are you sure?</h4>
                                <p>Do you want to delete this user?</p>
                                <a href="{% url 'delete_user' usr.user_id.id %}" class="btn btn-danger">
                                    Delete 
                                </a>
                            </div>
                            <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            </div>
                        </div>
                        </div>
                    </div>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

reff_no_api/templates/admin_login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Login/Sign In</h1>
    <form method="post" >
        {% csrf_token %}
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Username</label>
          <input type="text" name="username" class="form-control" id="exampleInputUsername1" aria-describedby="UserHelp">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input type="password" name="password" class="form-control" id="exampleInputPassword1">
        </div> 
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
{% endblock %}

reff_no_api/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Youth Empowerment </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    {% block head %}
        
    {% endblock head %}
        
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}
        
    {% endblock content %}
    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

reff_no_api/templates/footer.html
{% load static %}
<footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top">
    <div class="col mb-3 align-content-center text-center">
        <img src="{% static 'images/logo.jpg' %}" width="160" alt="">
      <p class="text-body-secondary">© 2024 | Made By Ritik Sinha</p>
    </div>

    <div class="col mb-3">

    </div>
    <div class="col mb-3 footer-links-mobile">
      <h5>Links</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
      </ul>
    </div>
    <div class="col mb-3 footer-links-mobile">
      <h5>Youth Empowerment Program</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">New Bus Stand,</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Bhatagaon, Raipur</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Chhattisgarh, 492013</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">contact: +918815234827</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">ceoyouthempowerment@gmail.com</a></li>
      </ul>
    </div>

    
  </footer>

reff_no_api/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div style="text-align: center;">
            <img src="{% static 'images/head_new.png' %}" class="img-fluid" style="object-fit: cover;" alt="...">
            <!-- <span class ="head-text">
                Youth Empowerment Program
            </span> -->
        </div>
        <!-- #carouselExample -->
        <div id="carouselExample" class="carousel slide mt-2">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="{% static 'images/1.png' %}" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="{% static 'images/2.png' %}" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="{% static 'images/3.png' %}" class="d-block w-100" alt="...">
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
        </div>
        <!-- About COmpnay -->
         <div class="mobile-view row pad-3rm pad-8rm ">
            <div class="col">
                <img src="{% static 'images/8.jpeg' %}" class="img-fluid" style="object-fit: cover;" alt="...">
            </div>
            <div class="col">
                <h2 class="head-text text-center mb-3">Business Opportunity</h2>
                
                <p class="about-us"><b>
                  The starting point for every journey is knowledge, if you have the knowledge about the path on which you have to travel, then the journey is going to be easier and more successful. We at Yep would emphasize that when you have registered yourself as a Yep Distributor, please read the Marketing Plan and understand the opportunity which lies in front of you to fulfil your dreams.
                  YEP Marketing Plan has been designed to be an equal business opportunity for all those who get associated with Yep. The Marketing Plan ensures that you earn in proportion to the efforts you put in and provides benefits such as leadership bonuses and pool income. These incomes are further enhanced by combining the downlines' performances so that it is always beneficial to create more leaders in your group. As the downline becomes successful, you become even more successful.
                </b>
                </p>
            </div>
         </div>

         <!-- Our Services  -->
        <div>
          <h2 class="head-text text-center mb-3">Our Services</h2>
          <div class="row">
            <div class="col d-flex align-items-center justify-content-center mb-3">
                <div class="card" style="width: 18rem; ">
                    <img src="{% static 'images/6.jpeg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                      <p class="card-text">Product 1</p>
                    </div>
                </div>
            </div>
            <div class="col d-flex align-items-center justify-content-center mb-3">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'images/pro5.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                      <p class="card-text">Product 2</p>
                    </div>
                </div>
            </div>
            <div class="col d-flex align-items-center justify-content-center mb-3">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'images/pro4.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                      <p class="card-text">Product 3</p>
                    </div>
                </div>
            </div>
          </div>
        </div>

        <div class="mt-5">
          <h2 class="head-text text-center mb-3">Our Team</h2>
          <div class="row text-center">
            <div class="col-lg-4 ">
              <div class="card">
                <div class="card-body">
                  <img src="{% static 'images/3.jpeg' %}" class="bd-placeholder-img rounded-circle" width="140" height="140" alt="Placeholder Image">
              <h2 class="fw-normal">Manoj Dewangan</h2>
              <p>CEO</p>
                </div>
                
              </div>
              
            </div><!-- /.col-lg-4 -->
          </div>
        </div>
    </div>
{% endblock content %}
    

reff_no_api/templates/navbar.html
{% load static %}
  <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom p-3">
    <div class="col-md-3 mb-2 mb-md-0">
      <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none logo">
        Youth Empowerment Program
      </a>
    </div>

    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
      <li><a href="/" class="nav-link px-2 ">Home</a></li>
      <li><a href="#" class="nav-link px-2">Products</a></li>
      <li><a href="#" class="nav-link px-2">About Us</a></li>
      <li><a href="#" class="nav-link px-2">Contacts</a></li>
    </ul>

    <div class="col-md-3 text-end">
      {% if user.is_authenticated %}
            <a href="{% url 'user_dash' %}" class="btn btn-primary me-2">{{user}}</a>
            <a href="{% url 'user_logout' %}" class="btn btn-danger">Logout</a>
        {% else %}
        <a href="{% url 'user_login' %}" class="btn btn-primary me-2">Login</a>
        <a href="{% url 'user_register' %}" class="btn btn-warning">Register</a>
        {% endif %}
    </div>
  </header>

reff_no_api/templates/user_register.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<style>
  /* Hide arrows in input of type number */
  input[type="number"]::-webkit-outer-spin-button,
  input[type="number"]::-webkit-inner-spin-button {
      -webkit-appearance: none;
      margin: 0;
  }

  input[type="number"] {
      -moz-appearance: textfield;
  }

  /*For password-validation checks */
  .password-requirements .requirement {
      color: grey;
      display: flex;
      align-items: center;
  }

  .password-requirements .requirement.valid {
      color: green;
  }

  .password-requirements .requirement.invalid {
      color: red;
  }

  .small-text {
      display: none;
      color: gray;
      font-size: 0.875rem;
  }

  .checkmark {
      display: inline-block;
      width: 18px;
      height: 18px;
      margin-right: 8px;
      border-radius: 50%;
      border: 2px solid grey;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 12px;
  }

  .checkmark::before {
      content: "";
      display: none;
  }

  .requirement.valid .checkmark::before {
      content: "✔";
      display: block;
  }

</style>
{% endblock head %}
  
{% block content %}
<div class="container mt-5">
    <h2>Create Account</h2>
    
    {% if ref_user %}
    <h4>Referred by : {{ref_user}}</h4>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <!-- Username Field -->
        <div class="mb-3">
          <label for="username" class="form-label">Username<span class="text-danger">*</span></label>
          <input type="text" class="form-control" id="username" name="username" required maxlength="255">
          <p class="text-danger" id="usernameError" style="display: none;">Username already taken</p>
        </div>

        <!-- First Name Field -->
        <div class="mb-3">
            <label for="first_name" class="form-label">First Name<span class="text-danger">*</span></label>
            <input type="text" class="form-control" id="id_first_name" name="first_name" required maxlength="255">
            <small class="text-danger" id="firstNameError" style="display: none;">Only letters are allowed for First Name</small>
        </div>

        <!-- Last Name Field -->
        <div class="mb-3">
            <label for="last_name" class="form-label">Last Name<span class="text-danger">*</span></label>
            <input type="text" class="form-control" id="id_last_name" name="last_name" required maxlength="255">
        </div>

        <!-- Email Field -->
        <div class="mb-3">
            <label for="email" class="form-label">Email Address <span class="text-danger">*</span> </label>
            <input type="email" class="form-control" id="id_email_id" name="email" required maxlength="255">
        </div>
        <p class="text-danger" id="emailError" style="display: none;">Please enter a valid email address</p>

        <!-- Mobile No Field -->
        <div class="mb-3">
          <label for="mobile_no" class="form-label">Mobile Number <span class="text-danger">*</span></label>
          <input type="text" class="form-control" id="id_mobile_no" name="mobile_no" required maxlength="255">
          <p class="text-danger" id="mobileError" style="display: none;">Mobile Number Already Registered</p>
        </div>

        <!-- Password Field -->
        <div class="mb-3">
            <label for="password" class="form-label">Password<span class="text-danger">*</span></label>
            <input type="password" class="form-control" id="id_password" name="password" required maxlength="255">
        </div>
        <div class="password-requirements mt-2" id="password-requirements">
          <div id="password-length" class="requirement">
              <span class="checkmark"></span> Password must be at least 8 characters long
          </div>
          <div id="password-uppercase" class="requirement">
              <span class="checkmark"></span> Contains uppercase letter (A-Z)
          </div>
          <div id="password-lowercase" class="requirement">
              <span class="checkmark"></span> Contains lowercase letter (a-z)
          </div>
          <div id="password-number" class="requirement">
              <span class="checkmark"></span> Contains digit (0-9)
          </div>
          <div id="password-special" class="requirement">
              <span class="checkmark"></span> Contains special character (!@#$%^&*)
          </div>
        </div>
        <div class="form-group">
          <label for="id_confirm_password" class="form-label">Confirm Password:</label>
          <input type="password" name="confirm_password" id="id_confirm_password" class="form-control" />
          <div class="password-feedback">
              <div class="invalid-feedback" id="confirm-password-error">Passwords do not match.</div>
              <div class="valid-feedback" id="confirm-password-match">Passwords match.</div>
          </div>
        </div>
        <div class="mt-2 text-center">
                <!-- Submit Button -->
        <button type="submit" class="btn btn-primary">Submit</button>
        </div>
  
    </form>
</div>
<script src="{% static 'js/user_register.js' %}"></script>


{% endblock content %}